import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'en' | 'hi';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
    }),
    {
      name: 'language-storage',
    }
  )
);

const translations = {
  en: {
    appName: 'Astrology App',
    panchang: 'Panchang',
    kundali: 'Kundali',
    coins: 'Coins',
    subscription: 'Subscription',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    loggingIn: 'Logging in...',
    welcomeTitle: 'Welcome!',
    welcomeDescription: 'Please complete your profile to get started',
    freeTrialWelcome: '🎉 Get your first month of premium access absolutely free!',
    name: 'Name',
    enterName: 'Enter your name',
    birthDate: 'Birth Date',
    birthTime: 'Birth Time',
    birthPlace: 'Birth Place',
    enterBirthPlace: 'Enter birth place',
    preferredLanguage: 'Preferred Language',
    continue: 'Continue',
    saving: 'Saving...',
    heroTitle: 'Discover Your Cosmic Journey',
    heroDescription: 'Explore ancient Vedic wisdom with modern astrology tools',
    heroFreeTrial: 'New users get their first month of premium access FREE!',
    explorePanchang: 'Explore Panchang',
    generateKundali: 'Generate Kundali',
    panchangFeature: 'Hindi Panchang',
    panchangFeatureDesc: 'Daily Hindu calendar with auspicious timings',
    kundaliFeature: 'Kundali Generation',
    kundaliFeatureDesc: 'Detailed birth chart analysis and matching',
    coinsFeature: 'Coin System',
    coinsFeatureDesc: 'Purchase coins for premium features',
    premiumFeature: 'Premium Access',
    premiumFeatureDesc: 'First month FREE, then ₹30/month',
    ctaTitle: 'Ready to unlock your destiny?',
    ctaDescription: 'Get started with your FREE first month of premium access',
    subscribeCta: 'Start Free Trial',
    panchangTitle: 'Hindi Panchang',
    panchangDescription: 'View daily Hindu calendar information',
    selectDate: 'Select Date',
    tithi: 'Tithi',
    nakshatra: 'Nakshatra',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    yoga: 'Yoga',
    karana: 'Karana',
    festivals: 'Festivals',
    noPanchangData: 'No Panchang data available for this date',
    kundaliTitle: 'Kundali Generation',
    kundaliDescription: 'Generate your personalized birth chart',
    enterBirthDetails: 'Enter your birth details to generate Kundali',
    generating: 'Generating...',
    birthDetails: 'Birth Details',
    date: 'Date',
    time: 'Time',
    place: 'Place',
    planetaryPositions: 'Planetary Positions',
    houses: 'Houses',
    premiumRequired: 'Premium subscription required to view detailed Kundali analysis',
    upgradeForDetails: 'Upgrade to Premium to view detailed analysis',
    loginRequired: 'Login Required',
    loginRequiredDesc: 'Please login to access this feature',
    coinsTitle: 'Coin Balance',
    coinsDescription: 'Purchase coins to unlock premium features',
    yourBalance: 'Your Balance',
    purchase: 'Purchase',
    purchasing: 'Purchasing...',
    subscriptionTitle: 'Premium Subscription',
    subscriptionDescription: 'Unlock all premium features with our monthly subscription',
    premiumPlan: 'Premium Plan',
    month: 'Month',
    freeFirstMonth: 'First Month FREE!',
    freeTrialActive: 'Your free trial is active!',
    enjoyingFreeTrial: 'Enjoying your free trial',
    freeTrialInfo: 'After your free trial ends, continue enjoying premium features for just ₹30/month',
    daysRemaining: '{{days}} days remaining',
    feature1: 'Detailed Kundali analysis',
    feature2: 'Advanced compatibility matching',
    feature3: 'Extended Panchang information',
    feature4: 'Personalized predictions',
    feature5: 'Priority support',
    activePremium: 'Active Premium Member',
    subscribe: 'Subscribe Now',
    processing: 'Processing...',
    paymentSuccess: 'Payment Successful!',
    paymentSuccessDesc: 'Your premium subscription is now active',
    paymentFailed: 'Payment Failed',
    paymentFailedDesc: 'There was an issue processing your payment',
    tryAgain: 'Try Again',
    backToHome: 'Back to Home',
    adminPanel: 'Admin Panel',
    adminDescription: 'Manage Panchang data and application settings',
    addPanchang: 'Add Panchang',
    addPanchangDesc: 'Add new Panchang data for a specific date',
    festivalsPlaceholder: 'Enter festivals separated by commas',
    adding: 'Adding...',
    accessDenied: 'Access Denied',
    adminOnly: 'This page is only accessible to administrators',
    loading: 'Loading...',
    stripeSetupTitle: 'Stripe Configuration',
    stripeSetupDescription: 'Configure Stripe payment settings',
    stripeSecretKey: 'Stripe Secret Key',
    allowedCountries: 'Allowed Countries',
    countriesHelp: 'Enter country codes separated by commas (e.g., IN,US,GB)',
    saveConfiguration: 'Save Configuration',
    aiChatTitle: 'AI Kundali Predictions',
    aiChatDescription: 'Get personalized predictions from our AI astrologer',
    aiChatRate: '₹5 per minute',
    startChat: 'Start AI Chat',
    endChat: 'End Chat',
    chatActive: 'Chat Active',
    elapsedTime: 'Elapsed Time',
    estimatedCost: 'Estimated Cost',
    insufficientCoins: 'Insufficient coins to start chat. Please purchase more coins.',
    purchaseCoins: 'Purchase Coins',
    chatEnded: 'Chat session ended',
    totalCost: 'Total Cost',
    minutes: '{{minutes}} min',
    askQuestion: 'Ask about your birth chart...',
    sendMessage: 'Send',
    aiTyping: 'AI is typing...',
    chatWelcome: 'Welcome! I am your AI astrologer. Ask me anything about your birth chart and I will provide personalized predictions based on your planetary positions.',
    chatInstructions: 'You can ask about career, relationships, health, finances, or any specific aspect of your life.',
  },
  hi: {
    appName: 'ज्योतिष ऐप',
    panchang: 'पंचांग',
    kundali: 'कुंडली',
    coins: 'सिक्के',
    subscription: 'सदस्यता',
    admin: 'व्यवस्थापक',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    loggingIn: 'लॉगिन हो रहा है...',
    welcomeTitle: 'स्वागत है!',
    welcomeDescription: 'शुरू करने के लिए कृपया अपनी प्रोफ़ाइल पूरी करें',
    freeTrialWelcome: '🎉 अपना पहला महीना प्रीमियम एक्सेस बिल्कुल मुफ्त पाएं!',
    name: 'नाम',
    enterName: 'अपना नाम दर्ज करें',
    birthDate: 'जन्म तिथि',
    birthTime: 'जन्म समय',
    birthPlace: 'जन्म स्थान',
    enterBirthPlace: 'जन्म स्थान दर्ज करें',
    preferredLanguage: 'पसंदीदा भाषा',
    continue: 'जारी रखें',
    saving: 'सहेजा जा रहा है...',
    heroTitle: 'अपनी ब्रह्मांडीय यात्रा की खोज करें',
    heroDescription: 'आधुनिक ज्योतिष उपकरणों के साथ प्राचीन वैदिक ज्ञान का अन्वेषण करें',
    heroFreeTrial: 'नए उपयोगकर्ताओं को पहला महीना प्रीमियम एक्सेस मुफ्त मिलता है!',
    explorePanchang: 'पंचांग देखें',
    generateKundali: 'कुंडली बनाएं',
    panchangFeature: 'हिंदी पंचांग',
    panchangFeatureDesc: 'शुभ समय के साथ दैनिक हिंदू कैलेंडर',
    kundaliFeature: 'कुंडली निर्माण',
    kundaliFeatureDesc: 'विस्तृत जन्म कुंडली विश्लेषण और मिलान',
    coinsFeature: 'सिक्का प्रणाली',
    coinsFeatureDesc: 'प्रीमियम सुविधाओं के लिए सिक्के खरीदें',
    premiumFeature: 'प्रीमियम एक्सेस',
    premiumFeatureDesc: 'पहला महीना मुफ्त, फिर ₹30/महीना',
    ctaTitle: 'अपनी किस्मत को अनलॉक करने के लिए तैयार हैं?',
    ctaDescription: 'अपने मुफ्त पहले महीने के प्रीमियम एक्सेस के साथ शुरुआत करें',
    subscribeCta: 'मुफ्त ट्रायल शुरू करें',
    panchangTitle: 'हिंदी पंचांग',
    panchangDescription: 'दैनिक हिंदू कैलेंडर जानकारी देखें',
    selectDate: 'तिथि चुनें',
    tithi: 'तिथि',
    nakshatra: 'नक्षत्र',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    yoga: 'योग',
    karana: 'करण',
    festivals: 'त्योहार',
    noPanchangData: 'इस तिथि के लिए कोई पंचांग डेटा उपलब्ध नहीं है',
    kundaliTitle: 'कुंडली निर्माण',
    kundaliDescription: 'अपनी व्यक्तिगत जन्म कुंडली बनाएं',
    enterBirthDetails: 'कुंडली बनाने के लिए अपने जन्म विवरण दर्ज करें',
    generating: 'बनाया जा रहा है...',
    birthDetails: 'जन्म विवरण',
    date: 'तिथि',
    time: 'समय',
    place: 'स्थान',
    planetaryPositions: 'ग्रह स्थिति',
    houses: 'भाव',
    premiumRequired: 'विस्तृत कुंडली विश्लेषण देखने के लिए प्रीमियम सदस्यता आवश्यक है',
    upgradeForDetails: 'विस्तृत विश्लेषण देखने के लिए प्रीमियम में अपग्रेड करें',
    loginRequired: 'लॉगिन आवश्यक',
    loginRequiredDesc: 'इस सुविधा तक पहुंचने के लिए कृपया लॉगिन करें',
    coinsTitle: 'सिक्का शेष',
    coinsDescription: 'प्रीमियम सुविधाओं के लिए सिक्के खरीदें',
    yourBalance: 'आपका शेष',
    purchase: 'खरीदें',
    purchasing: 'खरीदा जा रहा है...',
    subscriptionTitle: 'प्रीमियम सदस्यता',
    subscriptionDescription: 'हमारी मासिक सदस्यता के साथ सभी प्रीमियम सुविधाओं को अनलॉक करें',
    premiumPlan: 'प्रीमियम योजना',
    month: 'महीना',
    freeFirstMonth: 'पहला महीना मुफ्त!',
    freeTrialActive: 'आपका मुफ्त ट्रायल सक्रिय है!',
    enjoyingFreeTrial: 'अपने मुफ्त ट्रायल का आनंद ले रहे हैं',
    freeTrialInfo: 'आपके मुफ्त ट्रायल के समाप्त होने के बाद, केवल ₹30/महीना में प्रीमियम सुविधाओं का आनंद लेते रहें',
    daysRemaining: '{{days}} दिन शेष',
    feature1: 'विस्तृत कुंडली विश्लेषण',
    feature2: 'उन्नत अनुकूलता मिलान',
    feature3: 'विस्तारित पंचांग जानकारी',
    feature4: 'व्यक्तिगत भविष्यवाणियां',
    feature5: 'प्राथमिकता समर्थन',
    activePremium: 'सक्रिय प्रीमियम सदस्य',
    subscribe: 'अभी सदस्यता लें',
    processing: 'प्रोसेस हो रहा है...',
    paymentSuccess: 'भुगतान सफल!',
    paymentSuccessDesc: 'आपकी प्रीमियम सदस्यता अब सक्रिय है',
    paymentFailed: 'भुगतान विफल',
    paymentFailedDesc: 'आपके भुगतान को संसाधित करने में समस्या थी',
    tryAgain: 'पुनः प्रयास करें',
    backToHome: 'होम पर वापस जाएं',
    adminPanel: 'व्यवस्थापक पैनल',
    adminDescription: 'पंचांग डेटा और एप्लिकेशन सेटिंग्स प्रबंधित करें',
    addPanchang: 'पंचांग जोड़ें',
    addPanchangDesc: 'किसी विशिष्ट तिथि के लिए नया पंचांग डेटा जोड़ें',
    festivalsPlaceholder: 'अल्पविराम से अलग किए गए त्योहार दर्ज करें',
    adding: 'जोड़ा जा रहा है...',
    accessDenied: 'पहुंच अस्वीकृत',
    adminOnly: 'यह पृष्ठ केवल व्यवस्थापकों के लिए सुलभ है',
    loading: 'लोड हो रहा है...',
    stripeSetupTitle: 'स्ट्राइप कॉन्फ़िगरेशन',
    stripeSetupDescription: 'स्ट्राइप भुगतान सेटिंग्स कॉन्फ़िगर करें',
    stripeSecretKey: 'स्ट्राइप सीक्रेट की',
    allowedCountries: 'अनुमत देश',
    countriesHelp: 'अल्पविराम से अलग किए गए देश कोड दर्ज करें (जैसे, IN,US,GB)',
    saveConfiguration: 'कॉन्फ़िगरेशन सहेजें',
    aiChatTitle: 'AI कुंडली भविष्यवाणी',
    aiChatDescription: 'हमारे AI ज्योतिषी से व्यक्तिगत भविष्यवाणियां प्राप्त करें',
    aiChatRate: '₹5 प्रति मिनट',
    startChat: 'AI चैट शुरू करें',
    endChat: 'चैट समाप्त करें',
    chatActive: 'चैट सक्रिय',
    elapsedTime: 'बीता हुआ समय',
    estimatedCost: 'अनुमानित लागत',
    insufficientCoins: 'चैट शुरू करने के लिए अपर्याप्त सिक्के। कृपया अधिक सिक्के खरीदें।',
    purchaseCoins: 'सिक्के खरीदें',
    chatEnded: 'चैट सत्र समाप्त हुआ',
    totalCost: 'कुल लागत',
    minutes: '{{minutes}} मिनट',
    askQuestion: 'अपनी जन्म कुंडली के बारे में पूछें...',
    sendMessage: 'भेजें',
    aiTyping: 'AI टाइप कर रहा है...',
    chatWelcome: 'स्वागत है! मैं आपका AI ज्योतिषी हूं। अपनी जन्म कुंडली के बारे में मुझसे कुछ भी पूछें और मैं आपकी ग्रह स्थितियों के आधार पर व्यक्तिगत भविष्यवाणियां प्रदान करूंगा।',
    chatInstructions: 'आप करियर, रिश्ते, स्वास्थ्य, वित्त, या अपने जीवन के किसी विशिष्ट पहलू के बारे में पूछ सकते हैं।',
  },
};

export function useLanguage() {
  const { language, setLanguage } = useLanguageStore();

  const t = (key: keyof typeof translations.en, params?: Record<string, any>): string => {
    let text = translations[language][key] || translations.en[key];
    
    if (params) {
      Object.keys(params).forEach((param) => {
        text = text.replace(`{{${param}}}`, String(params[param]));
      });
    }
    
    return text;
  };

  return { language, setLanguage, t };
}
