/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatSession {
  'startTime' : Time,
  'endTime' : [] | [Time],
  'userId' : Principal,
  'totalCost' : bigint,
  'isActive' : boolean,
  'totalMinutes' : bigint,
}
export interface Kundali {
  'userId' : Principal,
  'generatedAt' : Time,
  'houses' : string,
  'planetaryPositions' : string,
  'birthDetails' : { 'date' : string, 'time' : string, 'place' : string },
}
export interface Panchang {
  'tithi' : string,
  'sunrise' : string,
  'date' : string,
  'yoga' : string,
  'festivals' : Array<string>,
  'sunset' : string,
  'nakshatra' : string,
  'karana' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'languagePreference' : string,
  'freeTrialEnd' : Time,
  'birthDate' : string,
  'birthTime' : string,
  'isPremium' : boolean,
  'coinBalance' : bigint,
  'name' : string,
  'birthPlace' : string,
  'registrationTime' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addPanchang' : ActorMethod<[Panchang], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deductCoins' : ActorMethod<[bigint], undefined>,
  'endChatSession' : ActorMethod<[], undefined>,
  'getActiveChatSession' : ActorMethod<[], [] | [ChatSession]>,
  'getAllPanchang' : ActorMethod<[], Array<Panchang>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatSessionHistory' : ActorMethod<[Principal], Array<ChatSession>>,
  'getKundali' : ActorMethod<[], [] | [Kundali]>,
  'getPanchang' : ActorMethod<[string], [] | [Panchang]>,
  'getRatePerMinute' : ActorMethod<[], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFreeTrialActive' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveKundali' : ActorMethod<[Kundali], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startChatSession' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoinBalance' : ActorMethod<[bigint], undefined>,
  'updateSubscriptionStatus' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];